# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010iclg225-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/l210/work/ec23b1029/ec23b1029/ec23b1029.cache/wt [current_project]
set_property parent.project_path /home/l210/work/ec23b1029/ec23b1029/ec23b1029.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/jump.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/add4_v.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/alu.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/immGen.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/insMemory.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/MUX.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/regFile.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/progCount.v}
  /home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/new/mem_arbiter.v
  /home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/new/vlsu.v
  /home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/new/config_unit.v
  /home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/new/vector_decoder.v
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/m2x1.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/ctrlLogic.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/datapath.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/vregfile.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/fdlogic.v}
  /home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/new/vector_controller.v
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/vect_mul.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/vreg_addr_input.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/datMemory.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/wblogic.v}
  {/home/l210/work/ec23b1029/RISCV_PROJECT/RISCV_NEW.srcs/sources_1/imports/RISC-V Cube/top.v}
}
synth_design -top datapath -part xc7z010iclg225-1L
write_checkpoint -noxdef datapath.dcp
catch { report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb }
